@startuml

enum SenderActions {}

interface ISender {
  + send<T>(action: string, data: T)
}

SenderActions <.right. ISender::send

interface ICard {
  + getDeck(): string
  + getFields(): Record<string, string>
}

interface IEntity {
  createIfNotExists(name: string)
}

interface IDeck extends IEntity {
}

interface IModel extends IEntity {
}

interface IExporter {
  + export(cards: Array<ICard>)
}

IExporter ..> IEntity

@enduml